### ISSUE TITLE
GLBuoys link in Header not working

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#17]
Clicking on GLBuoys in Logo, header does not resolve.

Looks like the attempted link is (for example) > http://glbuoys.glos.us/45179/#aboutBuoyPortal

Should this be going to the home page instead (I thought that's what it used to do)?

**Comment by kristinschrader** [comment]
My memory was that it went all the way back to glos.us, which was not the
intuitive outcome. It could go back to GLbuoys homepage


Kristin Schrader
Great Lakes Observing System
NOAA Great Lakes Environmental Research Lab
734-741-2294
glos.us <http://www.glos.us>




Like our Facebook page
<https://www.facebook.com/GreatLakesObservingSystem/?ref=aymt_homepage_panel>
Follow our Twitter feed <https://twitter.com/GLOSystem>

**Comment by kkoch** [comment]
@kristinschrader no that was the Portal misbehavior (which we still have an open issue tracker on).  GLBuoys was always a split logo where the left side went to glos.us but the right text went (I thought) to the GLBuoys homepage.  Or Greg might have set it to go to a separate about page but that obviously isn't working.

**Comment by gcutrell** [comment]
@kkoch Fixed.
