### ISSUE TITLE
Out of bounds values Plotting Tool

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#18]
Ron Muzzi reports > 

While checking the data for our buoys on this page:

    http://glbuoys.glos.us/tools/plotter?data_type=buoy&units=eng&locs=45162

![image](https://user-images.githubusercontent.com/6392982/40742464-a14af036-641c-11e8-9c11-2fa48a9179f1.png)

There are some out of bounds values for Wind Speed (and some of the other parameters as well).  You can see this on the attached screen shot.

Your plot page shows a Wind Speed value of -19436 on May 29, 03:00 UTC.

I think I can see what may be causing this.  It may be in the processing of missing data.  We do not upload any value for missing data, but may fill it in later.

From our logs, we uploaded this XML file named noaa-45162-apn_20180529_030654.xml:

<?xml version="1.0" encoding="ISO-8859-1"?>
<messages>
<message>
<station>45162</station>
<date>05/29/2018 02:40:00</date>
<met>
   <atmp1>14.200</atmp1>
   <dompd>2.06</dompd>
   <dp002>20.020</dp002>
   <gust1>2.0188</gust1>
   <mwdir>164.76</mwdir>
   <tp002>5.23</tp002>
   <wdir1>283.088</wdir1>
   <wspd1>0.8032</wspd1>
   <wtmp1>13.248</wtmp1>
   <wvhgt>0.05</wvhgt>
   <zox10>111.1</zox10>
   <zox9>14.10</zox9>
</met>
</message>
<message>
<station>45162</station>
<date>05/29/2018 03:00:00</date>
<met>
   <dompd>2.02</dompd>
   <dp002>20.011</dp002>
   <mwdir>15.92</mwdir>
   <tp002>5.24</tp002>
   <wvhgt>0.07</wvhgt>
   <zox10>111.1</zox10>
   <zox9>14.09</zox9>
</met>
</message>
</messages>

This contains some missing data values.  In the next cycle we uploaded those missing data values  along with the new data in a file named noaa-45162-apn_20180529_032457.xml:

<?xml version="1.0" encoding="ISO-8859-1"?>
<messages>
<message>
<station>45162</station>
<date>05/29/2018 03:00:00</date>
<met>
   <atmp1>15.690</atmp1>
   <gust1>0.8232</gust1>
   <wdir1>171.811</wdir1>
   <wspd1>0.2963</wspd1>
   <wtmp1>13.250</wtmp1>
</met>
</message>
<message>
<station>45162</station>
<date>05/29/2018 03:20:00</date>
<met>
   <atmp1>15.594</atmp1>
   <dompd>1.98</dompd>
   <dp002>20.011</dp002>
   <gust1>0.7056</gust1>
   <mwdir>140.38</mwdir>
   <tp002>5.24</tp002>
   <wdir1>329.775</wdir1>
   <wspd1>0.0817</wspd1>
   <wtmp1>13.239</wtmp1>
   <wvhgt>0.06</wvhgt>
   <zox10>111.0</zox10>
   <zox9>14.08</zox9>
</met>
</message>
</messages>

Is it possible that this is confusing the data processing?

P.S. I'm currently updating our software to provide you with some more data types per your request.  While working on that that, our system inadvertently re-uploaded the data set for the entire year in a single file.  Sorry about that!  I'll let you know when we're uploading the new values.

Thanks,
Ron Muzzi, EE 
U.S. Department of Commerce 
National Oceanic and Atmospheric Administration 
Great Lakes Environmental Research Laboratory 
4840 South State Road 
Ann Arbor, MI 48108 USA 
810-662-5718
ron.muzzi@noaa.gov

**Comment by gcutrell** [comment]
I know what the issue is. Have to wait till next week when Todd returns on how to fix it.

**Comment by gcutrell** [comment]
Fixed.
