### ISSUE TITLE
45022 45024 45026 temp nodes & metric/english conversion

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#19]
(See email thread to DMAC from Russ Miller. I assume he's referring to GLBuoys but let me know if this is also a Portal issue). Let me know if you need the referenced .nc files >

3)
On 45024 and 45026 I think the metric to english conversion for the top node only is too high, metric looks ok.  Only the top node seems affected on those buoys, and only the us units on the parameter table.

2) 
On Mon, Jun 4, 2018 at 7:23 PM, Russ Miller <rusmil@umich.edu> wrote:
I just noticed that the english <>metric conversion looks strange for the top three nodes as well.

On Mon, Jun 4, 2018 at 6:34 PM, Russ Miller <rusmil@umich.edu> wrote:

1) 
Hi, I finally go the temperature string running at 45022 Little Traverse Bay.

I'm noticing the the top two temperature nodes at 3m and 7m depth are reading correctly (ie, matching the xml file) on the line graph but reading 1C higher on the text parameter list above.  

I'm attaching two upload.xml files for comparison in case they're deleted as they're ingested.

Thanks!
Russ

**Comment by gcutrell** [comment]
It was a rounding issue. Should be fixed.
