### ISSUE TITLE
Add Canadian buoys

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#20]
- [x] User requested access to 45142 (Canadian buoy with NDBC feed) in GLBuoys (does show in Portal)

Also should add the following if reasonable:

- [x] 45147 (in Lake St. Clair)

- [x] 45154 (Huron - actually Georgian Bay)

- [x] 45136 (Lake Superior)

**Comment by gcutrell** [comment]
Just grouped 45147 45154 into the Huron menu. There are a number of non-Great Lake buoys so we might eventually want to make another category. Not sure what to call it.

**Comment by kkoch** [comment]
Thanks.  Maybe just call it Other?
