### ISSUE TITLE
Buoys incorrectly displaying "unavailable" 

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#23]
Several buoys are displaying a status of unavailable but when you click through to their data page it appears current:
45161, 45002, 45014, 45180, 45005, 45147

![image](https://user-images.githubusercontent.com/6392982/41872214-2a69f7b4-788f-11e8-8f6b-e7410549187c.png)

![image](https://user-images.githubusercontent.com/6392982/41872231-348822d4-788f-11e8-8686-f0dc710584fd.png)

**Comment by gcutrell** [comment]
@kkoch I can't replicate this.

**Comment by kkoch** [comment]
@gcutrell It's the same today.  Look at Muskegon buoy 45161 on main glbuoys page.  Status reads 'currently unavailable' but if you click on the asset page it shows current data as of 8:40am today.

**Comment by gcutrell** [comment]
Fixed. Issue of changing missing data values from NaN to null.
