### ISSUE TITLE
omoecc buoys

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#24]
OMOECC_O2 (Lake Ontario) not showing in GLBuoys and we actually have data from this one.

_E1 also not showing (although we don't have results from them right now).  I have an email in to my contact on whether these will be online this year.  Although O2 went in the water during IAGLR.

**Comment by gcutrell** [comment]
Thanks. This buoy I believe was causing GLBuoys to crash multiple times last week so I removed it. I need to figure out why it was causing the crash before I can add it back. Hopefully this week....

**Comment by kkoch** [comment]
Weird. Looks good in Portal which in this particular case is probably more important so whenever you get a chance.

**Comment by gcutrell** [comment]
Added it back to GLBuoys
