### ISSUE TITLE
GLBuoys not responding

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#29]
Users unable to connect to GLBuoys (noticed at about 3:15 today)

**Comment by beckypearson** [comment]
It is a significantly long loading time for me at 3:35, and I cannot load it on my mobile phone.

**Comment by gcutrell** [comment]
Back up. I started/stopped the server. Seems like something got hung up or some kind of memory issue that hasn't happened before. I'll see if the logs reveal anything to why it happened.

**Comment by kkoch** [comment]
Seems good. Closing
