### ISSUE TITLE
Data Chart not matching actual data (NDBC???)

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#32]
User (Jason Thurman jt78808@yahoo.com) reports that the data shown for 45147 doesn't match up with the graphs if you click on one of the values. For example, Wind Speed. Also, the wave height graph doesn't have any information on it at all.

I verified that the wind speed on the station page is showing 19.4 kts at 2:00pm ET.  This calibrates with what I see on the Portal and NDBC.  However, if you open the graph, the value shows at 3.9 (with .csv as 3.88768). 
>>> I did a random check of a few buoys and the same chart vs. data  issue appears on all the NDBC-only buoys, but not our normal ones.  I did not notice a cross-buoy issue with wind speed.

**Comment by gcutrell** [comment]
Error in python code. Fixed.
