### ISSUE TITLE
Download tool not working?

### ISSUE THREAD

**Issue by tslawecki** [glos/GLBuoys#33]
Went to 45013 through GLBuoys, clicked download. 

Once in download, none of the dynamic boxes (e.g. buoy ID) would populate.

@gcutrell, please look into this.

@kkoch, please advise if if you think this issue should go into a different repo ...

**Comment by kkoch** [comment]
That's where I would have put it.




Kathy
_____________________________________
Kathy Koch
Data Curator
Contractor (LimnoTech / GLOS)
501 Avis Drive, Ann Arbor, MI  48108
Office: 734-332-1200     email: kkoch@limno.com<mailto:kkoch@limno.com>
LimnoTech           www.limno.com<http://www.limno.com>
________________________________

**Comment by kkoch** [comment]
I've got a few minutes. I'll got try to beat it up in various browsers and see if I can replicate.

**Comment by kkoch** [comment]
Okay I was able to replicate in IE.  Works great in FF and Chrome but no go in IE10.  

![image](https://user-images.githubusercontent.com/6392982/47859276-5be71700-ddc4-11e8-94ae-181036d6c801.png)

**Comment by tslawecki** [comment]
@gcutrell, I just confirmed the same as @kkoch - OK in Chrome, fail in IE.

**Comment by kkoch** [comment]
I also tried running dev tools with all the various flavors of IE and it did not work for any of them.

**Comment by gcutrell** [comment]
Makes sense. IE is tough to deal with. Is it worth trying to fix when only 3% of users use IE?

**Comment by tslawecki** [comment]
Show a notice to IE users noting it doesn't work and recommending they switch. One js example at https://www.learningjquery.com/2017/05/how-to-use-javascript-to-detect-browser



________________________________

**Comment by gcutrell** [comment]
From my research the error should not occur in Edge but I have not tried it. There is now an alert for the 3% of GLBuoy users that the tool does not support Internet Explorer.
