### ISSUE TITLE
Google Tag Manager GTM issues for GLBuoys

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#9]
See MyGLOS issues #153 for details but these two are related.  This has high priority.

In case it was lost in a past email GLOS will be getting a large increase in user activity at glbuoys.glos.us Monday and we need to get GTM working for the website so there won’t be any interruptions once the activity starts up. I have the javascript script setup (hopefully everything will work) but I need your help and experience to get the GTM side set up. 

To echo gregs note. The glbuoys.glos.us website is expected to get 2500 active users a day.  500,000 page views per month starting next Tuesday.    This traffic tracking is paramount.

**Comment by gcutrell** [comment]
Big thanks to @gitchrisadams and Devra for helping get GTM going!
